version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          name: Run Maven Tests with Coverage
          command: mvn clean verify
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:checkstyle
      - run:
          name: Update README with Checkstyle Badge
          command: |-
            # Vérifie si le fichier Checkstyle existe
            if [ ! -f target/checkstyle-result.xml ]; then
          echo "Checkstyle report not found: target/checkstyle-result.xml"
            COLOR="grey"
            MESSAGE="No_Report"
            else
            # Analyse le rapport Checkstyle
            ERRORS=$(grep -o '<error' target/checkstyle-result.xml | wc -l)
          
            # Détermine le statut du badge
            if [ "$ERRORS" -eq 0 ]; then
            COLOR="green"
            MESSAGE="Passing"
            else
            COLOR="red"
            MESSAGE="${ERRORS}_Errors"
            fi
            fi
            
            # Génère l'URL du badge
            BADGE_URL="https://img.shields.io/badge/Checkstyle-${MESSAGE}-${COLOR}"
            
            # Met à jour le fichier README.md
            sed -i "s|!\[Checkstyle\](.*)|![Checkstyle](${BADGE_URL})|" README.md

      - run:
          name: Commit Updated README
          command: |-
            git config --global user.email "ci@example.com"
            git config --global user.name "CircleCI Bot"
            git add README.md
            git commit -m "Update Checkstyle Badge [ci skip]" || echo "No changes to commit"
            git push https://$GH_TOKEN@github.com/<RachidOuahsouni>/<ceri-m1-techniques-de-test>.git HEAD
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site/jacoco
          destination: jacoco-report
      - store_artifacts:
          path: target/site/checkstyle.html
          destination: checkstyle-report
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

workflows:
  build-and-test:
    jobs:
      - test-java
